baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'File Finder'
theme = 'file-finder-theme'

[params]
  algoliaAppId = os.Getenv "ALGOLIA_APP_ID"
  algoliaSearchKey = os.Getenv "ALGOLIA_SEARCH_KEY"
  